### ISSUE TITLE
Indentation with tabs

### ISSUE THREAD

**Issue by DRSDavidSoft** [dinhani/vscode-section-divider#1]
### Description
Pressing <kbd>Alt</kbd> + <kbd>D</kbd> when indentation is set to **tabs** doesn't generate correct comments:

<img width="508" alt="indent-comment" src="https://user-images.githubusercontent.com/4673812/53536362-5b188480-3b1b-11e9-9cef-66f1dc3408e4.png">

This is not an issue with **spaces** indentation:
<img width="475" alt="indent-correct" src="https://user-images.githubusercontent.com/4673812/53536430-9fa42000-3b1b-11e9-8545-bafffc45bf50.png">

Could you please add support for tabs indentation?

**Comment by dinhani** [comment]
I fixed it and deployed it now.

It should work fine with the latest release, 1.2.0.

**Comment by DRSDavidSoft** [comment]
@dinhani Thank you, it works perfectly!
