### ISSUE TITLE
Feature Request: Stata Comment

### ISSUE THREAD

**Issue by Layla2001** [dinhani/vscode-section-divider#13]
Hello, thanks for this helpful plug-in. Could I request for some improvement on the Stata comments?

In Stata, there are two types of comments starting with * or //,
now the default is like 
*======
* 
*======

However, I am thinking changing this to
// =======
//
// =======

I am wondering if there is some customization can be made

**Comment by dinhani** [comment]
@Layla2001 
Thanks for your request.

It was not possible, but I release a new version (2.4.0) where it is now possible to configure this. So ensure you have the last available version installed.

Add this configuration to your VSCode configuration file:

```json
"divider.overrides": {
    "stata": ["//"]
}
```
