### ISSUE TITLE
Secondary section

### ISSUE THREAD

**Issue by DRSDavidSoft** [dinhani/vscode-section-divider#2]
### Feature request
Can you please add support for **secondary sections** (i.e. _sub-section_)?

#### Example
- <kbd>Alt</kbd> + <kbd>D</kbd>

   ```
   // =====================================================================
   // THIS IS THE PRIMARY HEADER
   // =====================================================================
   ```

- <kbd>Alt</kbd> + <kbd>_Shift_</kbd> + <kbd>D</kbd>
   ```
   // ---------------------------------------------------------------------
   // this is the secondary header
   // ---------------------------------------------------------------------
   ```

**Comment by dinhani** [comment]
Added this functionality in the new 2.0.0 version, but using <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>D</kbd> as default shortcut instead because I think it is easier to type using only one hand.
